repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8 
    hooks:
      - id: ruff
        args: ["--fix"] 

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1  
    hooks:
      - id: mypy
        verbose: true
        entry: bash -c 'mypy "$@" || true' --