name: fes-ml-aev

channels:
  - conda-forge
  - openbiosim/label/emle

dependencies:
  - ambertools
  - ase
  - compilers
  - cudatoolkit<11.9
  - deepmd-kit
  - eigen
  - loguru
  - openmm>=8.1
  - openmm-torch
  - openmmforcefields
  - openff-toolkit
  - openff-interchange
  - nnpops
  - pip
  - pybind11
  - pytorch
  - python
  - pyyaml
  - sire
  - torchani
  - pygit2
  - xtb-python
  - pip:
    - git+https://github.com/chemle/emle-engine.git@feature_aev
    - git+https://github.com/openmm/openmm-ml.git
    - coloredlogs
    - mace-torch
