name: fes-ml-aev

channels:
  - conda-forge
  - openbiosim/label/emle

dependencies:
  - ambertools
  - compilers
  - cudatoolkit<11.9
  - eigen
  - loguru
  - openmm>=8.3
  - openmm-torch
  - openmm-ml
  - openmmforcefields
  - openff-toolkit
  - openff-interchange
  - nnpops
  - pip
  - pybind11
  - pytorch=*=*cuda*
  - python
  - pyyaml
  - sire
  - torchani
  - pygit2
  - pip:
    - git+https://github.com/chemle/emle-engine.git
    - coloredlogs
    - mace-torch
