name: fes-ml-aev

channels:
  - conda-forge
  - openbiosim/label/emle

dependencies:
  - ase
  - compilers
  - eigen
  - loguru
  - cmake
  - pip
  - pybind11
  - pytorch-gpu
  - python>3.11
  - pyyaml
  - torchani
  - openff-toolkit-base
  - openff-interchange-base
  - h5py
  - pip:
    - git+https://github.com/chemle/emle-engine.git@feature_aev
    - coloredlogs
