name: fes-ml

channels:
  - conda-forge
  - openbiosim/label/emle

dependencies:
  - ase
  - compilers
  - eigen
  - loguru
  - cmake
  - pip
  - pybind11
  - pytorch-gpu
  - python<3.11
  - pyyaml
  - torchani
  - xtb-python
  - openff-toolkit-base
  - openff-interchange-base
  - h5py
  - pip:
    - git+https://github.com/lab-cosmo/librascal.git
    - git+https://github.com/chemle/emle-engine.git
    - coloredlogs